/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    CISTPortConfig: typeof import('./src/components/stpConfig/CISTPortConfig.vue')['default']
    CommonTable: typeof import('./src/components/common/CommonTable.vue')['default']
    ConfigureTabs: typeof import('./src/components/common/ConfigureTabs.vue')['default']
    ConfigUser: typeof import('./src/components/userManage/ConfigUser.vue')['default']
    CustomBreadCrumb: typeof import('./src/components/layouts/CustomBreadCrumb.vue')['default']
    CustomLayoutHeader: typeof import('./src/components/layouts/CustomLayoutHeader.vue')['default']
    DragUpload: typeof import('./src/components/common/DragUpload.vue')['default']
    EditButtons: typeof import('./src/components/common/EditButtons.vue')['default']
    EditFooter: typeof import('./src/components/common/EditFooter.vue')['default']
    Iconfont: typeof import('./src/components/layouts/Iconfont.vue')['default']
    IntCheckbox: typeof import('./src/components/common/IntCheckbox.vue')['default']
    IntSwitch: typeof import('./src/components/common/IntSwitch.vue')['default']
    LacpPortConfig: typeof import('./src/components/lacpConfig/LacpPortConfig.vue')['default']
    LacpPortStatistscs: typeof import('./src/components/lacpConfig/LacpPortStatistscs.vue')['default']
    LacpPortStatus: typeof import('./src/components/lacpConfig/LacpPortStatus.vue')['default']
    LacpSettings: typeof import('./src/components/lacpConfig/LacpSettings.vue')['default']
    LacpSystemStatus: typeof import('./src/components/lacpConfig/LacpSystemStatus.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    MessageTip: typeof import('./src/components/common/MessageTip.vue')['default']
    MSTIMap: typeof import('./src/components/stpConfig/MSTIMap.vue')['default']
    MSTIPortConfig: typeof import('./src/components/stpConfig/MSTIPortConfig.vue')['default']
    MSTIPriority: typeof import('./src/components/stpConfig/MSTIPriority.vue')['default']
    NavMenuSider: typeof import('./src/components/layouts/NavMenuSider.vue')['default']
    PingAddress: typeof import('./src/components/systemConfig/PingAddress.vue')['default']
    PortAutoSpeedLimit: typeof import('./src/components/portConfig/PortAutoSpeedLimit.vue')['default']
    PortFlowDetail: typeof import('./src/components/portConfig/PortFlowDetail.vue')['default']
    PortFlowStatistics: typeof import('./src/components/portConfig/PortFlowStatistics.vue')['default']
    PortIsolate: typeof import('./src/components/portConfig/PortIsolate.vue')['default']
    PortModel: typeof import('./src/components/portConfig/PortModel.vue')['default']
    PortSpeedLimit: typeof import('./src/components/portConfig/PortSpeedLimit.vue')['default']
    PortStormLimit: typeof import('./src/components/portConfig/PortStormLimit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoftwareUpgarde: typeof import('./src/components/systemConfig/SoftwareUpgarde.vue')['default']
    StpBridgeSettings: typeof import('./src/components/stpConfig/StpBridgeSettings.vue')['default']
    StpBridgeStatus: typeof import('./src/components/stpConfig/StpBridgeStatus.vue')['default']
    StpCISTPortStatus: typeof import('./src/components/stpConfig/StpCISTPortStatus.vue')['default']
    StpPortStatistics: typeof import('./src/components/stpConfig/StpPortStatistics.vue')['default']
    SystemAddressManage: typeof import('./src/components/systemConfig/SystemAddressManage.vue')['default']
    SystemConfigManagement: typeof import('./src/components/systemConfig/SystemConfigManagement.vue')['default']
    SystemSSHStatus: typeof import('./src/components/systemConfig/SystemSSHStatus.vue')['default']
    SystemTelnetStatus: typeof import('./src/components/systemConfig/SystemTelnetStatus.vue')['default']
    TitleTab: typeof import('./src/components/common/TitleTab.vue')['default']
    UploadButton: typeof import('./src/components/common/UploadButton.vue')['default']
    VlanAccessPort: typeof import('./src/components/vlanConfig/VlanAccessPort.vue')['default']
    VlanHybridPort: typeof import('./src/components/vlanConfig/VlanHybridPort.vue')['default']
    VlanLinkMode: typeof import('./src/components/vlanConfig/VlanLinkMode.vue')['default']
    VlanManagement: typeof import('./src/components/vlanConfig/VlanManagement.vue')['default']
    VlanTrunkPort: typeof import('./src/components/vlanConfig/VlanTrunkPort.vue')['default']
  }
}
